spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/weiapp
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: wx_